# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-03 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='neighbourhood',
        ),
        migrations.RemoveField(
            model_name='business',
            name='user',
        ),
    ]
