# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-31 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_auto_20191031_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='user',
        ),
    ]
