# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-01 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_remove_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hood',
        ),
    ]
